### PR TITLE
Mate strand fix 2

### PR DESCRIPTION
**Pull request by jrobinso**
Second iteration of mate strand fix.  This uses the actual cram records, as implied in the spec.

### CODE REVIEW

**Comment by cmdcolin** [comment]
You can try doing

    yarn lint --fix

Also is this line necessary?

    if(mate.flags) mate.reverseComplemented = !!(mate.flags && Constants.CRAM_M_REVERSE)

The isMateReverseComplemented function seems to cover this case more thoroughly than this check does

**Comment by jrobinso** [comment]
Thanks for the yarn tip.  I will learn to use that,  it should be much easier than matching your style by hand.  It does not work out-of-the-box,  I'm getting an "eslint" command not found error.

WRT the mate.reverseComplemented line.   The purpose of that is to set the reverseComplemented property on the mate.   There is some redundancy here,  but I did not want a mate object that sometimes had that flag set (intra slice) and sometimes did not (detached).

However,  in retrospect perhaps we should not add this property to mate at all.   That is where it belongs, in my opinion,  but is not where the spec places it.    Rather,  perhaps we should just update cramRecord.flags with the correct value here.   In other words "fix" the BAM flags, that is retsore "bam.flags" to the value it had in the original BAM file,  at least wrt mate strand.    This is what the latest draft 3.0 spec and psuedo code implies should be done.   Ditto on the TLEN field,  it should be restored to its BAM file with intra-slice mate information.    I will close this PR and submit another along those lines.

**Comment by cmdcolin** [comment]
You might need to run "yarn" and then "yarn lint --fix", the eslint is installed as a devDependency so I think it shouldn't give a command not found

**Comment by jrobinso** [comment]
Actually since merging the latest to my local branch npm install fails
altogether,  I think that is the real problem.   I get an empy node_modules
directory after running it.    I'm still looking at it.     Are you able to
"npm install" this project from a fresh directory?

**Comment by jrobinso** [comment]
It seems to hang after the 404 error for "event-stream@3.3.6". 

kl-test:cram-js jrobinso$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/iconv-lite-95c1841e/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/iconv-lite-95c1841e/.travis.yml'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/iconv-lite-95c1841e/Changelog.md'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/iconv-lite-95c1841e/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/iconv-lite-95c1841e/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/amqplib-25da1cb9/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/amqplib-25da1cb9/callback_api.js'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/amqplib-25da1cb9/CHANGELOG.md'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/scoped-regex-6b97d34f/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/scoped-regex-6b97d34f/index.js'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/scoped-regex-6b97d34f/license'
WARN tar ENOENT: no such file or directory, open '/Users/jrobinso/igv-team Dropbox/James Robinson/projects/cram-js/node_modules/.staging/scoped-regex-6b97d34f/readme.md'
npm ERR! code E404
npm ERR! 404 Not Found: event-stream@3.3.6
```

**Comment by jrobinso** [comment]
OK, fixed after clearing everything, forcing a cache clear,  rebooting, and reinstalling NPM.   Now what was I doing?

**Comment by cmdcolin** [comment]
@jrobinso that actually was possibly a bug that needed fixing on our part, the event-stream 3.3.6 was actually tied to a bad bug and was unpublished from npm, so thanks for pointing that out

I have bumped some dependencies on the master branch, so if you try a `git pull origin master` and re-run `npm install` I think it'll work more cleanly

**Pull request closed without merging**
