### PR TITLE
Typescript build with esm module in package.json

### PR DESCRIPTION
**Pull request by cmdcolin**
Similar to changes in other modules (bam, gff, indexedfasta, generic-filehandle, etc)

### CODE REVIEW

**Comment by cmdcolin** [comment]
CC @rbuels in case you are interested

changes the repo to use tsc to compile, just runs over the js, and creates esm module that is about 50% the bundle size

**Review by rbuels — APPROVED** [review]
looks good to me, can merge and re-release when ready!

**Comment by cmdcolin** [comment]
Tested with the new cram-bundle.js generated by webpack and it works in the browser

```
<html>
  <head>
    <script src="https://unpkg.com/@gmod/cram/dist/cram-bundle.js"></script>
    <script>
      const { IndexedCramFile, CramFile, CraiIndex } = window.gmodCRAM

      // open local files
      const indexedFile = new IndexedCramFile({
        cramUrl: 'volvox-sorted.cram',
        index: new CraiIndex({
          url: 'volvox-sorted.cram.crai',
        }),
        seqFetch: async (seqId, start, end) => {
          return ''
        },
        checkSequenceMD5: false,
      })

      // example of fetching records from an indexed CRAM file.
      // NOTE: only numeric IDs for the reference sequence are accepted.
      // For indexedfasta the numeric ID is the order in which the sequence names appear in the header

      // Wrap in an async and then run
      run = async () => {
        const records = await indexedFile.getRecordsForRange(0, 10000, 20000)
        records.forEach(record => {
          console.log(`got a record named ${record.readName}`)
          if (record.readFeatures != undefined) {
            record.readFeatures.forEach(({ code, pos, refPos, ref, sub }) => {
              if (code === 'X') {
                console.log(
                  `${record.readName} shows a base substitution of ${ref}->${sub} at ${refPos}`,
                )
              }
            })
          }
        })
      }

      run()
    </script>
  </head>
  <body>
    <h1>Hello world</h1>
  </body>
</html>
```

**Comment by cmdcolin** [comment]
could try merge for now

**Pull request merged**
