### PR TITLE
Update source code example in README for transforming seqName/seqId

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds code to the README for performing the nameToId and idToName transformations

My prettier formatting tool automatically made the spacing 4 and quoting double, I can try to make it single/2 space if it is better

### CODE REVIEW

**Comment by cmdcolin** [comment]
I believe the only case that a SQ line would not exist would be for "embedded refseqs" which is a pretty obscure part of CRAM, and we may not even properly supprot it. Therefore, that could lend evidence to just making our API use seqName directly instead of seqIds

**Comment by cmdcolin** [comment]
rebased on master and added a prettierrc (my code editor auto formats source code blocks in the readme with prettier settings so this helps with that). it duplicates with the .eslintrc but maybe helpful anyways

**Comment by rbuels** [comment]
This makes me think we ought to add some methods to make this easier for people. Maybe a `nameToId` method that lazily parses the SAM header as shown in this example?

**Comment by cmdcolin** [comment]
could be a "polymorphic" use of getRecordsForRange where if it's a string, handles one way, otherwise, another

or, a new API

something to have an easy to use API I think would ideal

**Comment by cmdcolin** [comment]
since this is the current way of doing things, might merge for now. can consider adding easier api in new version

**Pull request merged**
